### PR TITLE
modified:   views/login.handlebars

### PR DESCRIPTION
**Pull request by MatteoThomas**

### CODE REVIEW

**Review by k-ryanhunt — CHANGES_REQUESTED** [review]
character

**Review by JDavid337 — APPROVED** [review]
Changes look good

**Review by JDavid337 — APPROVED** [review]
changes look good to me!

**Review by JDavid337 — APPROVED** [review]

**Review by ncclymer — COMMENTED** [review]
spelling good

**Review by k-ryanhunt — APPROVED** [review]

**Pull request merged**
